### ISSUE TITLE
Guidelines for communicating with staff/EC about CoC incidents

### ISSUE THREAD

**Issue by kariljordan** [carpentries/coc-guidelines-taskforce#11]
The following Code of Conduct incident response procedure was developed collaboratively by The Carpentries Staff.

[Procedure](https://docs.google.com/document/d/184QJJAYz6GfTAP7vyUE2IYrqijHKkNotKTAuJaQpSI8/edit?usp=sharing)

From this procedure I will create a checklist for incidents that require an immediate response , i.e. the community member is removed from all Carpentries engagement.

We need to include language in the CoC that states staff/EC members pertinent to the operations of The Carpentries will be made aware of persons under review such that their privileges can be revoked.

**Feedback Request:** Please provide recommendations for how to phrase this type of statement by **17-February**. I will then add the statement to the CoC Documentation in the appropriate spot(s).

**Comment by karinlag** [comment]
@kariljordan Is it intentional that we have to request access to this document?

**Comment by karinlag** [comment]
I also want to have clarified, this is what you think should happen after a violation has been found, i.e. a situation has been resolved conclusively by the committee?

**Comment by kariljordan** [comment]
> @kariljordan Is it intentional that we have to request access to this document?

Not intentional. I will fix.

**Comment by kariljordan** [comment]
> I also want to have clarified, this is what you think should happen after a violation has been found, i.e. a situation has been resolved conclusively by the committee?

There may be instances when an immediate block on access is required. This procedure is for that case, and when a case is under review. If a community member is under CoC review we do not allow them to engage, is this correct?

**Comment by kariljordan** [comment]
Added [this PR](https://github.com/carpentries/handbook/pull/370) to the handbook, but it **will not be merged** until all of the Code of Conduct documentation has been revised.
