### ISSUE TITLE
Semantics in Code of Conduct - is "vacation" a reward?

### ISSUE THREAD

**Issue by ppival** [carpentries/coc-guidelines-taskforce#12]
In the resolutions section of the [Enforcement Manual](https://docs.carpentries.org/topic_folders/policies/code-of-conduct.html#enforcement-manual) of the Code of Conduct, is "vacation" the correct word? To me, a "vacation" is some sort of reward, and a *desired* thing. When someone does something wrong they're often asked to take a "leave without pay", and I kinda think maybe the word "vacation" should be replaced by "leave"...

@kariljordan

**Comment by kariljordan** [comment]
We've replaced the word "vacation" with "suspension" in the [revised enforcement guidelines](https://docs.google.com/document/d/1xKDJEzqDsxxx3k5mGg7uKl9wjVqusuEwbBG1cRQQv2o/edit). These guidelines are still being updated per the community feedback from the RFC, so feel free to make more recommendations. Thank you!

**Comment by kariljordan** [comment]
Once the documentation has been updated in the Google documents we will update the handbook and publish a blog post.
