### ISSUE TITLE
Suggestion: add a tldr section to Coc

### ISSUE THREAD

**Issue by maneesha** [carpentries/coc-guidelines-taskforce#13]
At an admin meeting it was brought up that the Code of Conduce can be a long or intimidating read, especially if someone is feeling upset.  Suggestion is to have a 2-3 bullet point condensed version that people can easily refer to even in a stressful situation.

**Comment by kariljordan** [comment]
@malvikasharan shared a short version of the CoC that I believe she was planning to use for CarpentryConnect or another non-Carpentries event. Malvika, can you post the link to that here? I'd like the documentation to be set up similar to the [code4lib](https://2018.code4lib.org/conduct/) Code of Conduct. @tracykteal recommended this as a model and to make separate documents for the reporting guidelines, enforcement manual, etc.

**Comment by kariljordan** [comment]
Also @maneesha yes, a tldr is a great idea. I plan to draft a CoC landing page with short bullets and links to each of the documents.

**Comment by tracykteal** [comment]
We can't use a different version of the CoC at Carpentries related events. But we can have a more concise landing page. So, good idea to develop that along with updates to CoC guidelines.

**Comment by malvikasharan** [comment]
@kariljordan here is the CarpentryConnect Manchester page where we have used a short version: https://software.ac.uk/ccmcr19. This was agreed with the CoCc.

**Comment by tracykteal** [comment]
Thanks @malvikasharan. That's great. A good shorter description that still links to the full CoC. That's perfect.

**Comment by kariljordan** [comment]
@malvikasharan do you mind if we use the text you formulated as a tl;dr for our CoC in the handbook?

**Comment by malvikasharan** [comment]
@kariljordan Please feel free to add it to handbook :)

**Comment by kariljordan** [comment]
@maneesha added the tl;dr to the handbook (will be merged this afternoon), so closing this issue.
