### ISSUE TITLE
Request for Comments: Code of Conduct Incident Reporting Guidelines

### ISSUE THREAD

**Issue by kariljordan** [carpentries/coc-guidelines-taskforce#6]
[This document](https://docs.google.com/document/d/1SLA30oIx90AGYTPlE7MBkGPXjw0Jy9aAxuicG02w7tE/edit) outlines the proposed Reporting Guidelines for The Carpentries Code of Conduct. Please comment below or leave a comment directly on the Google document if there is language that is not clear about these guidelines.

**Deadline: 17-February 2019**

**Comment by elliewix** [comment]
I've added my comments to the google doc.  Thanks!

**Comment by kariljordan** [comment]
@tracykteal As of 19-Feb I have revised the reporting guidelines per the feedback we received from the community. Four community members provided feedback.

**Comment by kariljordan** [comment]
All of the comments have been incorporated into this document, so I am closing this issue. Thank you everyone!
