### ISSUE TITLE
Request for Comments: Code of Conduct Enforcement Guidelines

### ISSUE THREAD

**Issue by kariljordan** [carpentries/coc-guidelines-taskforce#9]
[This document](https://docs.google.com/document/d/1xKDJEzqDsxxx3k5mGg7uKl9wjVqusuEwbBG1cRQQv2o/edit) outlines the proposed Enforcement Guidelines for the Code of Conduct. Please comment below or leave a comment directly on the Google document if there is language that is not clear about these guidelines.

**Deadline: 17-February 2019**

**Comment by quirksahern** [comment]
Sounds reasonable, however is there a nicer way of presenting it as currently not an easy document to digest?

**Comment by kariljordan** [comment]
We wanted to be able to show the diffs, so the plan was to create a text document in markdown format and then transfer all of this information to the handbook for final review. I can definitely try to make it neater and easier to read!

**Comment by lexnederbragt** [comment]
Should these guidelines have provisions for when the reporter or reportee is a member of staff, the Executive Coouncil, or the CoC Committee?

**Comment by kariljordan** [comment]
@lexnederbragt I wanted to make sure you're aware that the guidelines include provisions for staff, EC, and CoCc

**Comment by kariljordan** [comment]
All of the comments have been incorporated into this document, so I am closing this issue. Thank you everyone!
